# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pruebaCeiba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper'
  pod 'AlignedCollectionViewFlowLayout'
  pod 'IQKeyboardManagerSwift','6.3.0'
  pod 'ZVProgressHUD', '~> 2.0.0'
  
  # Pods for pruebaCeiba

  target 'pruebaCeibaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pruebaCeibaUITests' do
    # Pods for testing
  end

end
